controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_recipe:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::recipe
